CREATE TABLE STUDENT (
    s_no VARCHAR2(3 BYTE) NOT NULL ,
    s_name VARCHAR2(9 BYTE) NOT NULL ,
    s_sex CHAR(2 BYTE) NOT NULL
);
INSERT INTO STUDENT VALUES ('001', 'KangKang', 'M ');
INSERT INTO STUDENT VALUES ('002', 'Mike', 'M ');
INSERT INTO STUDENT V